#!/bin/bash
cut -d ':' -f 1,6 /etc/passwd | sort

100-empty_casks

#!/bin/bash
find . -empty | rev | cut -d '/' -f 1 | rev

101-gifs

#!/bin/bash
find -type f -name "*.gif" | rev | cut -d "/" -f 1 | cut -d '.' -f 2- | rev | LC_ALL=C sort -f

102-acrostic

#!/bin/bash
cut -c 1 | paste -s -d ''
103-the_biggest_fan

#!/bin/bash
tail -n +2 | cut -f -1 | sort -k 1 | uniq -c | sort -rnk 1 | head -n 11 | rev | cut -d ' ' -f -1 | rev
README.md
